export const INIT_PRODUCT_DATA = "INIT_PRODUCT_DATA";
export const INIT_TRANSLATIONS = "INIT_TRANSLATIONS";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const SET_SEARCH_PRODUCTS = "SET_SEARCH_PRODUCTS";
export const SET_SEARCHING_STATUS = "SET_SEARCHING_STATUS";

export const INIT_REVIEWS = "INIT_REVIEWS";
