export enum AppActionsEnum {
  INIT_PRODUCT_DATA = 'INIT_PRODUCT_DATA',
  INIT_PRODUCT_DATA_SUCCESS = 'INIT_PRODUCT_DATA_SUCCESS',
  INIT_PRODUCT_DATA_FAILED = 'INIT_PRODUCT_DATA_FAILED',
  INIT_TRANSLATIONS = 'INIT_TRANSLATIONS',
  INIT_TRANSLATIONS_SUCCESS = 'INIT_TRANSLATIONS_SUCCESS',
  INIT_TRANSLATIONS_FALIED = 'INIT_TRANSLATIONS_FALIED',
}